apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: house-price-prediction
  template:
    metadata:
      labels:
        app: house-price-prediction
    spec:
      containers:
      - name: house-price-prediction
        image: drlamio/house-price-prediction-app:latest
        ports:
        - containerPort: 8080
