name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t house-price-prediction-app .

      - name: Log in to Heroku Docker registry
        run: echo "$HEROKU_API_KEY" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com

      - name: Push to Heroku Docker registry
        run: docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - name: Release on Heroku
        run: |
          curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
          -d '{
            "updates": [
              {
                "type": "web",
                "docker_image": "'"$(docker inspect registry.heroku.com/$HEROKU_APP_NAME/web:latest --format={{.Id}})"'"
              }
            ]
          }' \
          -H "Content-Type: application/json" \
          -H "Authorization
