name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t drlamio/house-price-prediction-app .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push drlamio/house-price-prediction-app:latest

      - name: Log in to Heroku Docker registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=${{ secrets.HEROKU_USERNAME }} --password-stdin registry.heroku.com

      - name: Push to Heroku Docker registry
        run: docker push registry.heroku.com/amescityhousingprediciton/web

      - name: Release on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl -n -X PATCH https://api.heroku.com/apps/amescityhousingprediciton/formation \
          -d '{
            "updates": [
              {
                "type": "web",
                "docker_image": "'"$(docker inspect registry.heroku.com/amescityhousingprediciton/web:latest --format={{.Id}})"'"
              }
            ]
          }' \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-container"
